env:
  global:
    - secure: "aVbcUL8J/yKV0tXQYzzbxrssnzxEJdiwd28ROWHBL00e/aBeyPS6Jz8ArHUoW2KfD0tkK1J281iErI9NaqQLOuxO4Qam1ZuqqNFvLzrZIzfAxm3BogEIEl+qb7mh3KgxPCuqIzfIalzMJq1j3/iq52oyhcpsGL0yqiH6AcQKp8WddFCGAA+ZW+t3Vkpq8Qo8p8kXbdrz2ZStNFpGdypS0WAQugfnGFfwUC4wmhRM/SdDJluzgLAh8fSVRxDwk9ZaOSbCfx/74iN8jNTZhINbp7ky5R8f4Y57p+6/3zfYHPnpO+IwbcDKO4+7SCe5HTzBAirNcsBLuXGmxCPEz8NIIZJpVTf08NotygEuufuNn/51fuL2Dkf2c4g9J4672Lbr1I7SXhPXLxUrKjCN9UNItFj7UlePSFzxqc97225ohI8TsL+grPOLtXaTRPO/rnfk/s+Yl7nWKSBlrdHZGoq/75TZq1V99oAdORw9g4wIj3+qLpiAbsdS+50nSmwUCWa/9SHiwBuLFnS1qQF2izo2b+P1hGfIjSOdyfmfOD0k14COM+7ES4mViEEGnVHTTHpHzh307UYRjk9hwQrFs6rv5sapGy/t6YnwlqfRpwrFY6S2/ZWpdNy8Z+hK8/Y3Z7OKnwkUNHUJYn281oTAxfBE09XSCZa9d6U2XoI3b0rDHkA=" # DOCKER_USER
    - secure: "cVqOmc/XkX96dTYa0MnqqiD5c6bGqYDUre+lMvuG89yPUHYuwx6UStm6y3ahyO967L6/WPJnaGqWyQjCMC2AF0YyQiuXBGYTAIZLy1Tt0ofvCwve3v5lKxCe+uwBdiiWk3Xdb+P8H23VyOOAUy6/bp0tHGkQcasF73fthiwvvOKp7pncAyb/zYYUnE+ZdytGxgVmPQ7Hrdo486dipO3rIT5sspteIpd8Y2pIhHaF0QAjdqjNPgCrEVVZpxJXFs3TJtrOzyX73fDjrlzOjb35Q4FSGRlCqlc8RYdF/FAZab8ag3Dnwmc39xC6SMtAlExDQkdul59QG0yaZPxS9TIaIAH7Fog6snlNiUJszl8sJnpErPYozDnfNyNnseB8jYTsnd19SHBGcDLtS/qBDJ00181ti2qZGMUWSem5Sjyfx/kFrQ0W1tkIew98IOJW6UvgFIlKLutLWXbSSm9/YwB7MDY46Q7YjvzqaU5F5FBAGBlj/VqeNkFANFL6VuobNHhVtPQR/IcYhdjLlCLEj7cg/n91qHdtvgdMAr+2LXMKlN4WElzOKzCdtSVz6f9KjxcARs6KnSCtYGfBsCDlJ1k4e2tcAs1VHZkY/Poo3zxdIiSEV6E3W0hvR2BGXq8yvOqYthoQNKQ/Uqx/RjfeHQD/2pkdVlR/l5zZxC0Wo+HOUBE=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=startx/sxapi-ui
    - RELEASE=0.1.4

sudo: required

services:
  - docker

before_install:
- docker pull startx/sxapi:testing
- docker images

script: ./travis.sh

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH" == "testing" ]; then echo "testing"; else echo $RELEASE ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
