env:
  global:
    - secure: "dX5uLxzRbyBE6W9hzHdi92CiTwe6wKr5kFHemfI/bWZXYAtzvHlf5CRx21RBFa6iqBbAdQYIIaxfIKwFM3zDASOW1uXyoaZJa0mU7CzFiYfNpYZm3WviJ0Gsx384HopbtkpTQSDkMaWigg9dYnFc9ajhbholSeXJbblDOde2nZ+PKRb8KrBuSb3jI6NAfkFkh7lTuKruBzJi1AfOrNmeo3JF9GuUmekNMO95SXci2NSjddeLbBMbAmsD3UkR8+ZVvcdiXG8PeUD5H2wgA1F3QdBwFF/2I63JjW+T30avI3JfugXS6C/36RS+oZqHOvRDSTNr9gwDTXfQipbvbh5/bqnPqsiTbgeSbFj6JikXwZ5kAzeYjZd2kWegTghegtNu3rBtjOvdVUg8upjkVsiIe41O0GxUTJdelO8UM+Nx8E+WucYizDwcY6693buKLP7rpfCJdKGv+Ddkexa5yxtxixiwc28kqQIsO6uuryS1v/6kzcoG5E8OoNEzV0ZZfuGW5Da+TLg0/BEyJbzwsMBC6wTrHngr4TLQKVcy8Nvrs80mXW2gml8J/UywYAAvIaM4pWC5oJ24A34TCJx9+w2FuZigfO8mv6fnN2lfh0++CIyvKM4hwwcRBHb+ns+YQT5GJazzzTwk1/N/gBYVwGKwDmVkPBNtaQbOKleXtp1meWE=" # DOCKER_EMAIL
    - secure: "UHFv8CVi4o3CloCw/R+kQPLaYyfDZXtAwgv+D00TQ6tjonTEn7kFhdXtLurCUFQW7gfM2LvIYaSGc2nVKWzrFgmXarbZBQgjZxu8AldHzebjPXy/pNCip15D1/Zo3nf7JC41Jt8WEvYaqqme8eORclJ5xVrXCbEAzU/Y3zv7BtiHHM8XV5ovolqMxCLdlJkQ87kvr1LPMDPvwWhV1JUdM8mQTB2qE0E7QQmXwvbHcN+HwEAs73GpVh6F5FZDa8zHIS0AypNw6Pv73EprymitbaqfRq5yNwR4xMYWhd+PORGqNWc0vh1R/wi2CbTT33aZFp5yz6B+wQX+GJrM0eTd/A4Cs3jFrcXswW89CoW5i4xNdqQFT33ULmr3l1qKETdBIXz6D22i62Yiv7evHJ4Hqq33so51l+UC+sT32DBa+6eoOVAXTQsX8nVa9bBOfyfQpBCV9N12HkoYlac3J7Hj5lpYb10g2XW0ULq2cegSOxBL5IPLORJnl3qsUUTcMa6biEfQ0CN3/ai3FOUANUdUMtaGHfHJzyk5cvnMxmqjAP4Jc3uQVALomFVkCEMj9/icymc9IyKl8RFGo4omnMOp3ML8UMOg070V6664oREVd9tU2UqoLweUE2y5ueVx99E9ccGpS9+Hk9xcH8wbv2swr+M6c1isrKSAPSrG57MLcrA=" # DOCKER_USER
    - secure: "lRKQSTlWjO5NWk+IgonFLw04aJHQ7NZNUDPbKHofeU88e4KRbHOzgkGjHA5nq3Htu/2P379LlRI6beaeK1Ptw7xTTRPxMGPcYCXFrZlew75G8K9lJwNQ8FEOzOz1bV4GiCUxOnFVv1QAJWW0BHwQLqF8m8E/QTGq8ejkb+7rhrHtreJ17iEZXV55qA7s6ny6iBE7Evwo37vaUp5gTfHUp1LXglzjUMjpvPuPICamzv9f9xi/cSJeJK+1ARA8c8SHskmjOFnlh9WNlxWOMiPLp7P6glZuCETQalYHDfQoEtzv8ocE+GSShojkL+pCje1PSxQ5tiBfQqMuXLPK/a/1QMJwSk49xwJH11EV11fxTQqJxZ0xUfs4YJ8VjyNBAaGhFIAJ4jcIx05SrK6bSJsmkzbLLOT/mTn1+aYAaRp02NQdcWbs9k512IOC3zbMcB8aoPUYZlMCON9eqVaeZtIv8PFOLQPI/xxrpyB3pZ4GX7gDbBIY1UbZez3/59/REuF5NaMwHFRz/a1Andc4yVYyN0HITmEEshEWAaw+alVpG5oKTLR+sy5cOrczDNvqjJl1ji7fyhStjCOLHOBYMH+3y02b9M+iXIK+JEOHBnps4vkDDuwQldT4FCIVNxpwyFs/fap8X0LK8HFhahrbE7RLUKRSQAd7yD9WqgJaLmFr+2M=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=startx/sxapi-ui
    - RELEASE=0.0.2

sudo: required

services:
  - docker

before_install:
- docker pull startx/sxapi:0.0.77
- docker images

script: ./travis.sh

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ "$TRAVIS_BRANCH" == "testing" ]; then echo "testing"; else echo $RELEASE ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
