app:
  image: startx/sxapi:latest
  container_name: "sxapi-ui-dev"
  mem_limit: 512m
  memswap_limit: 1g
  ports:
    - "8081:8081"
  volumes:
  - "./node_modules:/usr/src/app/node_modules:z"
  - "./test:/usr/src/app/test:z"
  - "./static:/usr/src/app/static:z"
  - "./package.json:/usr/src/app/package.json:z"
  - "./sxapi.json:/conf/sxapi.json:z"
  command: start
