app:
  image: startx/sxapi:latest
  container_name: "sxapi-ui-dev"
  mem_limit: 512m
  memswap_limit: 1g
  ports:
    - "8081:8081"
  volumes:
  - "./node_modules:/usr/src/app/node_modules:Z"
  - "./test:/usr/src/app/test:Z"
  - "./static:/usr/src/app/static:Z"
  - "./package.json:/usr/src/app/package.json:Z"
  - "./sxapi.json:/conf/sxapi.json:Z"
  working_dir: /usr/src/app
  entrypoint: /bin/sxapi start
