app_main:
  build: .
  container_name: "sxapi-ui-v0.0.4"
  mem_limit: 200m
  memswap_limit: 500m
  ports:
    - "8081:8081"

app:
  extends: app_main
  volumes:
    - "./sxapi.json:/conf/sxapi.json:ro" 
